apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy-app-2
  namespace: poc
  labels:
    app: hw-app-2
    kuma.io/service: hw-app-2 # Etiqueta para Kuma
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw-app-2
  template:
    metadata:
      labels:
        app: hw-app-2
        kuma.io/service: hw-app-2 # Etiqueta para Kuma
    spec:
      containers:
      - name: hw-container-app-2
        image: jaimehenao8126/poc-app-2:d8db383d47c575036f14206344269bd358165b93
        ports:
        - containerPort: 80
