apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy-app-2
annotations:
  notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocdnotification1
  notifications.argoproj.io/subscribe.on-sync-failed.slack: argocdnotification1
  notifications.argoproj.io/subscribe.on-health-degraded.slack: argocdnotification1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw-app-2
  template:
    metadata:
      labels:
        app: hw-app-2
    spec:
      containers:
      - name: hw-container
        image: jaimehenao8126/poc-app-2:eac556f809df69449858d3fa14da11df9647254b
        ports:
        - containerPort: 80
