apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy-app-2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw-app-2
  template:
    metadata:
      labels:
        app: hw-app-2
    spec:
      containers:
      - name: hw-container
        image: jaimehenao8126/poc-app-2:5d044df4f0a665a93db3125311324409ca0102f5
        ports:
        - containerPort: 80
