apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy-app-2
spec:
  replicas: 1  # Ajusta el número de replicas según tus necesidades
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw-app-2
  template:
    metadata:
      labels:
        app: hw-app-2
    spec:
      containers:
      - name: hw-container
        image: jaimehenao8126/poc-app-2:958b12c674e93e0b56cdfde4af5e898606060ca7
        ports:
        - containerPort: 80
