apiVersion: v1
kind: Service
metadata:
  name: hw-service-app-2
spec:
  selector:
    app: hw-app-2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort  # Cambiado a NodePort para Minikube
